version: '3.9'

services:
    mysql:
        image: mysql:8
        container_name: patient_mediscreen_sql
        restart: always
        environment:
            MYSQL_ROOT_USERNAME: root
            MYSQL_ROOT_PASSWORD: nico5310
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/data/db

    mongodb:
        image: mongo:latest
        container_name: note_mediscreen_mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: nico
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db


volumes:
    mysql_data:
    mongodb_data:



